### ISSUE TITLE
Hy I have Laptop 

### ISSUE THREAD

**Issue by oyeanu** [hshamsaldin/OpenCore-HP-840-G1-Haswel#1]
Can you please aad intel wifi kext because thy are now supported mac os

**Comment by oyeanu** [comment]
And tell me this efi work for big sur

**Comment by 3rroronly1** [comment]
I have link u can follow this guide for wifi fix
https://youtu.be/gkSApERhPTU
Mine worked intel 7260

**Comment by hshamsaldin** [comment]
Unfortunately, I no longer have such a laptop.
